[package]
name = "k8s-openapi-tests"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]
publish = false

[dependencies]
backtrace = "0.3.x"
bytes = "0.4.x"
k8s-openapi = { path = "../k8s-openapi" }
reqwest = "0.8.x"
serde = "1.0.x"
serde_derive = "1.0.x"
serde_yaml = "0.7.x"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.x", features = ["bcrypt", "errhandlingapi", "minwindef", "ncrypt", "wincrypt", "winnt"] }

[target.'cfg(not(windows))'.dependencies]
openssl = "0.10.x"

[features]
v1_7 = ["k8s-openapi/v1_7"]
v1_8 = ["k8s-openapi/v1_8"]
v1_9 = ["k8s-openapi/v1_9"]
v1_10 = ["k8s-openapi/v1_10"]
